name: mobile_burger
description: A Flutter app for Mobile Burgers restaurant.
version: 1.0.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  assets:
    - assets/images/
    - assets/itens_cardapio.json

  
  
  
